import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:3000';
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page = await context.newPage();
const errors = [];
page.on('pageerror',e=>errors.push(e.message));
let id;
try {
  await page.goto(base,{waitUntil:'networkidle'});
  await page.waitForSelector('tbody tr');
  assert.equal(await page.locator('h1').textContent(),'운영 대시보드');
  await page.screenshot({path:'screenshots/dashboard-final.png',fullPage:true});
  await page.getByRole('button',{name:'검사 세션',exact:true}).click();
  await page.getByRole('textbox',{name:'세션 검색'}).fill('ORI-001');
  assert.equal(await page.locator('tbody tr').count(),1);
  await page.getByRole('button',{name:'검색 지우기'}).click();
  await page.getByRole('button',{name:'새 검사 시작',exact:true}).click();
  await page.locator('.modal-course').first().click();
  await page.getByRole('button',{name:'세션 만들기',exact:true}).click();
  await page.waitForSelector('.created-session');
  const link=await page.getByRole('link',{name:'이 기기에서 검사 열기'}).getAttribute('href');
  id=new URL(link).searchParams.get('session');
  assert.ok(id);
  const tablet=await context.newPage();
  tablet.on('pageerror',e=>errors.push(e.message));
  await tablet.goto(base+'/tablet?session='+id,{waitUntil:'networkidle'});
  await tablet.waitForSelector('.consent-card');
  await tablet.screenshot({path:'screenshots/participant-consent.png',fullPage:true});
  assert.equal(await tablet.getByRole('button',{name:'나를 만나러 가기'}).isEnabled(),false);
  await tablet.locator('input[type=checkbox]').first().check();
  await tablet.getByRole('button',{name:'나를 만나러 가기'}).click();
  const responses=[4,3,5,4,2,2,4,1,2,4];
  for(let i=0;i<10;i++){
    await tablet.locator('.answer-options>button').nth(responses[i]-1).click();
    await tablet.getByRole('button',{name:i<9?'다음 질문':'내 응답 저장하기',exact:true}).click();
  }
  await tablet.waitForSelector('.ready-card');
  await tablet.getByRole('button',{name:/측정 시작/}).click();
  await tablet.waitForSelector('.measurement-card');
  for(let i=0;i<5;i++){
    const target=tablet.locator('.reaction-button.ready:not([disabled])');
    await target.waitFor({timeout:15000});
    await target.click();
    await tablet.waitForTimeout(250);
  }
  await tablet.waitForSelector('.participant-completed',{timeout:22000});
  await tablet.screenshot({path:'screenshots/participant-result.png',fullPage:true});
  const s=await (await fetch(`${base}/api/sessions/${id}`)).json();
  assert.equal(s.status,'completed');
  assert.equal(s.scores.E,100);
  assert.ok(s.metrics.samples>=300);
  assert.ok(s.metrics.reactionMs!==null);
  assert.equal(s.researchConsent,false);
  const csv=await (await fetch(`${base}/api/export?kind=raw&id=${id}`)).text();
  assert.ok(csv.includes('adc'));
  assert.ok(csv.includes(id));
  const json=await (await fetch(`${base}/api/export?format=json&id=${id}`)).json();
  assert.equal(json.project,'oriori_gsr');
  await page.getByRole('button',{name:'닫기',exact:true}).click();
  await page.getByRole('button',{name:'장비 & 설정',exact:true}).click();
  await page.getByLabel('감열지 너비').selectOption('58');
  await page.getByRole('button',{name:'설정 저장',exact:true}).click();
  await page.waitForSelector('.toast');
  let workspace=await (await fetch(base+'/api/workspace')).json();
  assert.equal(workspace.settings.paperWidth,'58');
  await page.getByLabel('감열지 너비').selectOption('80');
  await page.getByRole('button',{name:'설정 저장',exact:true}).click();
  await page.getByRole('button',{name:/^시작 가이드/}).click();
  await page.waitForSelector('.guide-download');
  await page.screenshot({path:'screenshots/guide.png',fullPage:true});
  const zip=await fetch(base+'/downloads/oriori_gsr.zip');
  assert.equal(zip.status,200);
  assert.equal(new Uint8Array(await zip.arrayBuffer())[0],80);
  await page.getByRole('button',{name:'운영 대시보드',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'screenshots/mobile-final.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.getByRole('button',{name:'메뉴 열기'}).click();
  await page.getByRole('button',{name:'데이터 보관함',exact:true}).click();
  await page.waitForSelector('.export-grid');
  assert.equal(await page.locator('.export-card').count(),3);
  assert.deepEqual(errors,[]);
  console.log('PASS: dashboard, navigation, search, session, consent, 10 questions, five reactions, result, raw/JSON export, settings persistence, ZIP, mobile.');
} finally {
  if(id) await fetch(`${base}/api/sessions/${id}`,{method:'DELETE'});
  await context.close();
  await browser.close();
}
